---
- name: Copy manifest app
  copy:
    src: diploma_app_deployment.yaml
    dest: /root/
    remote_src: no
    mode: 0644
    owner: root
    group: root
  when: "'masters' in group_names"

- name: Install app
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  shell: kubectl apply -f /root/diploma_app_deployment.yaml
  when: "'masters' in group_names"